{"uuid": "d85027c3-0ec3-4843-a836-14af12ba88e2", "children": ["8dea87db-167e-4d06-9720-a44aa8060680"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 0\n\n", "trace": "  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\_pytest\\fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\conftest.py\", line 33, in app\n    fixture = Application(browser=browser,base_url=web_config['baseUrl'])\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\fixture\\application.py\", line 10, in __init__\n    self.wd = webdriver.Firefox()\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\firefox\\webdriver.py\", line 181, in __init__\n    RemoteWebDriver.__init__(\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 269, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 360, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Admin\\PycharmProjects\\Python_training\\env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1651092953174, "stop": 1651092969544}], "start": 1651092953174, "stop": 1651092969679}